stakater-nordmart-review-ui:
  application:
    route:
       additionalLabels:
          router: default
    deployment:
      image:
        repository: https://nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud
        tag: 0.1.0
      env:
        REVIEW_API:
          # This is hardcoded!
          value: "https://review-gabbar-stage.apps.preprod.jlvwjls8.kubeapp.cloud/"